version: '3.9'
services:
    app:
        build: .
        ports:
            - '8000:8000'
        environment:
            - REDIS_HOSTNAME=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=${REDIS_PASSWORD}
    redis:
        image: redis:7.0-rc1-alpine
        ports:
            - '6379:6379'
        command: redis-server --requirepass ${REDIS_PASSWORD}
